version: '3.9'

services:
  db:
    image: postgres:16
    container_name: pg-notes-db
    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  postgrest:
    image: postgrest/postgrest
    container_name: postgrest-api
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://admin:secret@db:5432/notes
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_SCHEMA: public
      PGRST_OPENAPI_SERVER_PROXY_URI: http://localhost:3000

volumes:
  pgdata:
